server:
    port: 9091

spring:
    application:
        name: spring-boot-oauth2


security:
    oauth2:
        client:
            clientId: 502310427709663
            clientSecret: 514f6549095222374abf1bd069aaed3f
            accessTokenUri: https://graph.facebook.com/oauth/access_token
            userAuthorizationUri: https://www.facebook.com/dialog/oauth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
        resource:
            userInfoUri: https://graph.facebook.com/me